name: "Run tfsec with sarif upload"
description: "Run tfsec against terraform code base and upload the sarif output to the github repo"
author: "Owen Rumney"

inputs:
  working_directory:
    description: |
      Directory to run the action on, from the repo root.
      Default is . ( root of the repository)
    default: "."
    required: false
  sarif_file:
    description: The path to write the sarif report, defaults to tfsec.sarif
    default: tfsec.sarif
    required: false
  tfvars_file:
    description: The tfvars file to use for the scan
    required: false
  config_file:
    description: The path to the config file. (eg. ./tfsec.yml)
    required: false
  tfsec_args:
    description: |
      Space seperated args specified here will be added during tfsec execution.
      (eg. --verbose)
    required: false
  full_repo_scan:
    description: Scan the entire repository for Terraform issues
    required: false

runs:
  using: "composite"
  steps:
    - name: Run tfsec script
      env:
        INPUT_TFVARS_FILE: ${{ inputs.tfvars_file }}
        INPUT_CONFIG_FILE: ${{ inputs.config_file }}
        INPUT_TFSEC_ARGS: ${{ inputs.tfsec_args }}
        INPUT_FULL_REPO_SCAN: ${{ inputs.full_repo_scan }}
        INPUT_SARIF_FILE: ${{ inputs.sarif_file }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
      id: run
      shell: sh
      run: ${{ github.action_path }}/entrypoint.sh

outputs:
  tfsec-return-code:
    value: ${{ steps.run.outputs.tfsec_return_code }}
    description: "tfsec command return code"
branding:
  icon: "search"
  color: "gray-dark"
